swagger: "2.0"
info:
  version: "1.0.0"
  title: "Pactum Flow API"
basePath: "/api/flow/v1"
consumes:
  - "application/json"
  - "text/html"
produces:
  - "application/json"
  - "text/html"
  - "text/plain"
paths:
  /health:
    get:
      tags:
        - "HealthCheck"
      description: "check health"
      operationId: "getHealth"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    x-swagger-router-controller: "health.controller"
  /projects:
    get:
      tags:
        - "Project"
      description: "get projects"
      operationId: "getProjects"
      parameters:
        - in: "query"
          name: "key"
          description: "key of the project to fetch"
          type: "string"
        - in: "query"
          name: "name"
          description: "name of the project to fetch"
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    post:
      tags:
        - "Project"
      description: "create a new project"
      operationId: "postProject"
      parameters:
        - in: "body"
          name: "project"
          description: "project to create"
          required: true
          schema:
            $ref: "#/definitions/Project"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Project"
    x-swagger-router-controller: "project.controller"
  /projects/{id}:
    get:
      tags:
        - "Project"
      description: "get project with id"
      operationId: "getProject"
      parameters:
        - in: "path"
          name: "id"
          description: "project id to fetch"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Project"
    delete:
      tags:
        - "Project"
      description: "delete a project"
      operationId: "deleteProject"
      parameters:
        - in: "path"
          name: "id"
          description: "project id to delete"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    x-swagger-router-controller: "project.controller"
  /analyses:
    get:
      tags:
        - "Analyses"
      description: "get analyses"
      operationId: "getAnalyses"
      parameters:
        - in: "query"
          name: "projectId"
          description: "id of the project to fetch"
          type: "string"
        - in: "query"
          name: "version"
          description: "version of the project to fetch"
          type: "string"
        - in: "query"
          name: "branch"
          description: "branch of the project to fetch"
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Analyses"
    post:
      tags:
        - "Analyses"
      description: "create a new analysis"
      operationId: "postAnalysis"
      parameters:
        - in: "body"
          name: "analysis"
          description: "analysis to create"
          required: true
          schema:
            $ref: "#/definitions/Analysis"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Analysis"
    x-swagger-router-controller: "analysis.controller"
  /analyses/{id}:
    get:
      tags:
        - "Analyses"
      description: "get analysis with id"
      operationId: "getAnalysisById"
      parameters:
        - in: "path"
          name: "id"
          description: "analysis id to fetch"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Analysis"
    delete:
      tags:
        - "Analyses"
      description: "delete an analysis"
      operationId: "deleteAnalysis"
      parameters:
        - in: "path"
          name: "id"
          description: "analysis id to delete"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    x-swagger-router-controller: "analysis.controller"
  /interactions:
    get:
      tags:
        - "Interactions"
      description: "get interactions"
      operationId: "getInteractions"
      parameters:
        - in: "query"
          name: "analysisId"
          description: "id of the analysis"
          type: "string"
          required: true
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Interaction"
    post:
      tags:
        - "Interactions"
      description: "create a new interaction"
      operationId: "postInteractions"
      parameters:
        - in: "body"
          name: "interactions"
          description: "interactions to create"
          required: true
          schema:
            $ref: "#/definitions/Interactions"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Interaction"
    x-swagger-router-controller: "interaction.controller"
  /interactions/{id}:
    get:
      tags:
        - "Interactions"
      description: "get interaction with id"
      operationId: "getInteractionById"
      parameters:
        - in: "path"
          name: "id"
          description: "interaction id to fetch"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Interaction"
    x-swagger-router-controller: "interaction.controller"
  /flows:
    get:
      tags:
        - "Flows"
      description: "get flows"
      operationId: "getFlows"
      parameters:
        - in: "query"
          name: "analysisId"
          description: "analysis id of the flow to fetch"
          type: "string"
        - in: "query"
          name: "projectId"
          description: "project id of the flow to fetch"
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Flows"
    post:
      tags:
        - "Flows"
      description: "create a new flows"
      operationId: "postFlows"
      parameters:
        - in: "body"
          name: "flow"
          description: "flow to create"
          required: true
          schema:
            $ref: "#/definitions/Flows"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Flows"
    x-swagger-router-controller: "flow.controller"
  /flows/{id}:
    get:
      tags:
        - "Flows"
      description: "get flow with id"
      operationId: "getFlow"
      parameters:
        - in: "path"
          name: "id"
          description: "flow id to fetch"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Flow"
    x-swagger-router-controller: "flow.controller"
  /metrics/projects:
    get:
      tags:
        - "Metrics"
      description: "get project metrics"
      operationId: "getProjectMetrics"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    x-swagger-router-controller: "metric.controller"
  /metrics/analysis/{id}:
    get:
      tags:
        - "Metrics"
      description: "get analysis metrics"
      operationId: "getAnalysisMetrics"
      parameters:
        - in: "path"
          name: "id"
          description: "analysis id to fetch"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    x-swagger-router-controller: "metric.controller"
  /process/analysis:
    post:
      tags:
        - "Process"
      description: "process analysis"
      operationId: "postProcessAnalysis"
      parameters:
        - in: "body"
          name: "process body"
          description: "analysis to process"
          required: true
          schema:
            $ref: "#/definitions/ProcessAnalysis"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    x-swagger-router-controller: "processor.controller"
  /search/analyses:
    post:
      tags:
        - "Search"
      description: "search analyses"
      operationId: "postSearchAnalyses"
      parameters:
        - in: "body"
          name: "search"
          description: "search payload"
          required: true
          schema:
            $ref: "#/definitions/SearchIds"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Analyses"
    x-swagger-router-controller: "search.controller"
  /search/interactions:
    post:
      tags:
        - "Search"
      description: "search interactions"
      operationId: "postSearchInteractions"
      parameters:
        - in: "body"
          name: "search"
          description: "search payload"
          required: true
          schema:
            $ref: "#/definitions/SearchIds"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Interactions"
    x-swagger-router-controller: "search.controller"
  /search/flows:
    post:
      tags:
        - "Search"
      description: "search flows"
      operationId: "postSearchFlows"
      parameters:
        - in: "body"
          name: "search"
          description: "search payload"
          required: true
          schema:
            $ref: "#/definitions/SearchIds"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Flows"
    x-swagger-router-controller: "search.controller"
definitions:
  Project:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
    required:
     - "id"
     - "name"
  Analysis:
    type: "object"
    properties:
      projectId:
        type: "string"
      branch:
        type: "string"
      version:
        type: "string"
    required:
     - "projectId"
     - "branch"
     - "version"
  Analyses:
    type: "array"
    items:
      $ref: "#/definitions/Analysis"
  Interaction:
    type: "object"
    properties:
      analysisId:
        type: "string"
      provider:
        type: "string"
      flow:
        type: "string"
      request:
        type: "object"
      response:
        type: "object"
    required:
      - "analysisId"
      - "provider"
      - "flow"
      - "request"
      - "response"
  Interactions:
    type: "array"
    items:
      $ref: "#/definitions/Interaction"
  Flow:
    type: "object"
    properties:
      projectId:
        type: "string"
      analysisId:
        type: "string"
      name:
        type: "string"
      request:
        $ref: "#/definitions/FlowRequest"
      response:
        $ref: "#/definitions/FlowResponse"
    required:
     - "projectId"
     - "analysisId"
     - "name"
     - "request"
     - "response"
  Flows:
    type: "array"
    items:
      $ref: "#/definitions/Flow"
  FlowRequest:
    type: "object"
    properties:
      method:
        type: "string"
      path:
        type: "string"
      pathParams:
        type: "object"
      queryParams:
        type: "object"
      headers:
        type: "object"
    required:
     - "method"
     - "path"
  FlowResponse:
    type: "object"
    properties:
      statusCode:
        type: "number"
      headers:
        type: "object"
    required:
     - "statusCode"
  ProcessAnalysis:
    type: "object"
    properties:
      id:
        type: "string"
        minLength: 2
    required:
      - "id"
  SearchIds:
    type: "object"
    properties:
      ids:
        type: "array"
        items:
          type: "string"
    required:
      - "ids"
  HealthResponse:
    description: "Health Response"
    type: "object"
    properties:
      message:
        type: "string"
    example:
      message: "OK"