swagger: "2.0"
info:
  version: "1.0.0"
  title: "Pactum Flow API"
basePath: "/api/pactum/flow/v1"
consumes:
  - "application/json"
  - "text/html"
produces:
  - "application/json"
  - "text/html"
  - "text/plain"
paths:
  /health:
    get:
      tags:
        - "HealthCheck"
      description: "check health"
      operationId: "getHealth"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    x-swagger-router-controller: "health.controller"
  /project:
    get:
      tags:
        - "Project"
      description: "get projects"
      operationId: "getProjects"
      parameters:
        - in: "query"
          name: "key"
          description: "key of the project to fetch"
          type: "string"
        - in: "query"
          name: "name"
          description: "name of the project to fetch"
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    post:
      tags:
        - "Project"
      description: "create a new project"
      operationId: "postProject"
      parameters:
        - in: "body"
          name: "project"
          description: "project to create"
          required: true
          schema:
            $ref: "#/definitions/Project"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Project"
    x-swagger-router-controller: "project.controller"
  /project/{id}:
    get:
      tags:
        - "Project"
      description: "get project with id"
      operationId: "getProject"
      parameters:
        - in: "path"
          name: "id"
          description: "project id to fetch"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Project"
    delete:
      tags:
        - "Project"
      description: "delete a project"
      operationId: "deleteProject"
      parameters:
        - in: "path"
          name: "id"
          description: "project id to delete"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    x-swagger-router-controller: "project.controller"
  /analysis:
    get:
      tags:
        - "Analysis"
      description: "get analysis"
      operationId: "getAnalysis"
      parameters:
        - in: "query"
          name: "projectId"
          description: "id of the project to fetch"
          type: "string"
        - in: "query"
          name: "version"
          description: "version of the project to fetch"
          type: "string"
        - in: "query"
          name: "branch"
          description: "branch of the project to fetch"
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    post:
      tags:
        - "Analysis"
      description: "create a new analysis"
      operationId: "postAnalysis"
      parameters:
        - in: "body"
          name: "analysis"
          description: "analysis to create"
          required: true
          schema:
            $ref: "#/definitions/Analysis"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Analysis"
    x-swagger-router-controller: "analysis.controller"
  /analysis/{id}:
    get:
      tags:
        - "Analysis"
      description: "get analysis with id"
      operationId: "getAnalysisById"
      parameters:
        - in: "path"
          name: "id"
          description: "analysis id to fetch"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Analysis"
    delete:
      tags:
        - "Analysis"
      description: "delete an analysis"
      operationId: "deleteAnalysis"
      parameters:
        - in: "path"
          name: "id"
          description: "analysis id to delete"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    x-swagger-router-controller: "analysis.controller"
  /flow:
    get:
      tags:
        - "Flow"
      description: "get flows"
      operationId: "getFlows"
      parameters:
        - in: "query"
          name: "analysisId"
          description: "analysis id of the flow to fetch"
          type: "string"
        - in: "query"
          name: "projectId"
          description: "project id of the flow to fetch"
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    post:
      tags:
        - "Flow"
      description: "create a new flow"
      operationId: "postFlow"
      parameters:
        - in: "body"
          name: "flow"
          description: "flow to create"
          required: true
          schema:
            $ref: "#/definitions/Flow"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Flow"
    x-swagger-router-controller: "flow.controller"
  /flow/{id}:
    get:
      tags:
        - "Flow"
      description: "get flow with id"
      operationId: "getFlow"
      parameters:
        - in: "path"
          name: "id"
          description: "flow id to fetch"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Flow"
    delete:
      tags:
        - "Flow"
      description: "delete a flow"
      operationId: "deleteFlow"
      parameters:
        - in: "path"
          name: "id"
          description: "flow id to delete"
          required: true
          type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/HealthResponse"
    x-swagger-router-controller: "flow.controller"
definitions:
  Project:
    type: "object"
    properties:
      key:
        type: "string"
      name:
        type: "string"
    required:
     - "key"
     - "name"
  Analysis:
    type: "object"
    properties:
      projectId:
        type: "string"
      branch:
        type: "string"
      version:
        type: "string"
    required:
     - "projectId"
     - "branch"
     - "version"
  Flow:
    type: "object"
    properties:
      projectId:
        type: "string"
      analysisId:
        type: "string"
      name:
        type: "string"
      request:
        $ref: "#/definitions/FlowRequest"
      response:
        $ref: "#/definitions/FlowResponse"
    required:
     - "projectId"
     - "analysisId"
     - "name"
     - "request"
     - "response"
  FlowRequest:
    type: "object"
    properties:
      method:
        type: "string"
      path:
        type: "string"
      pathParams:
        type: "object"
      queryParams:
        type: "object"
      headers:
        type: "object"
    required:
     - "method"
     - "path"
  FlowResponse:
    type: "object"
    properties:
      statusCode:
        type: "number"
      headers:
        type: "object"
    required:
     - "statusCode"
  HealthResponse:
    description: "Health Response"
    type: "object"
    properties:
      message:
        type: "string"
    example:
      message: "OK"